### ISSUE TITLE
How to test recreating MainActivity by System ？

### ISSUE THREAD

**Issue by maoqis** [husaynhakeem/Androidx-SavedState-Playground#1]
How to test recreating MainActivity by System ？

**Comment by maoqis** [comment]
i get it ，Developer options -> Do not keep activities

**Comment by husaynhakeem** [comment]
Hey @maoqis. Yeah, that's one way of doing it, you could also use the command line to kill the app (and simulate the system killing your app)
```
adb shell am kill com.package.example
```

**Comment by maoqis** [comment]
thanks
