### ISSUE TITLE
SavedStateVMFactory was replaced by SavedStateViewModelFactory

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [husaynhakeem/Androidx-SavedState-Playground#3]
I think SavedStateViewModelFactory replaced SavedStateVMFactory, so SavedStateVMFactory can't be used anymore. Can you please show how to use SavedStateViewModelFactory instead?

If you update the versions, you will see that it's a breaking change . There is no SavedStateVMFactory anymore:

https://developer.android.com/jetpack/androidx/releases/lifecycle#lifecycle-viewmodel-savedstate-1.0.0-alpha02

Not only that, but I see more deprecated stuff being used here:

![image](https://user-images.githubusercontent.com/5357526/73160930-f54dc780-40f2-11ea-9755-eb0a698c4e00.png)

Can you please update the project and show how to use the new API ?

**Comment by husaynhakeem** [comment]
Updated the repo to the latest dependencies. Thanks for notifying me!

**Comment by AndroidDeveloperLB** [comment]
I suggest to update the article too, or make a new one, while on the previous one link to both.

Also, you missed those:

![image](https://user-images.githubusercontent.com/5357526/73527132-314a9a80-441b-11ea-8d47-d711eb81f958.png)


```
        viewModel = ViewModelProviders.of(this, factory).get(ViewModelWithSavedState::class.java)
        viewModel = ViewModelProviders.of(this).get(ViewModelWithoutSavedState::class.java)

```

You are supposed to use:
```
        viewModel = ViewModelProvider(this, factory).get(ViewModelWithSavedState::class.java)
        viewModel=ViewModelProvider(this).get(ViewModelWithoutSavedState::class.java)
```
